version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Build the react app to give an optimized production build
      - npm run build
  build:
    commands:
      # Copy the content of build folder into website s3 bucket
      - aws s3 sync build/ s3://1337giraffetickler.tk/
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://1337giraffetickler.tk/public/
artifacts:
  files:
    - '**/*'
  base-directory: build